name: tarot_verse_frontend
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.1
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  google_fonts: ^6.2.1
  flutter_hooks: ^0.20.5
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Lưu ý: Cả assets, fonts và uses-material-design đều phải nằm trong CÙNG MỘT khối 'flutter:'.
flutter:
  uses-material-design: true

  assets:
    - assets/tarot_cards.json
    - assets/images/

  fonts:
    - family: CinzelDecorative
      fonts:
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
        - asset: assets/fonts/CinzelDecorative-Black.ttf
          weight: 700